import re
import argparse
import matplotlib.pyplot as plt
import csv

def parse_modredundant(log_content):
    scan_info = None
    for i, line in enumerate(log_content):
        if "The following ModRedundant input section has been read:" in line:
            j = i + 1
            while j < len(log_content):
                mod_line = log_content[j].strip()
                if not mod_line or not re.match(r"^[DRAB]\s+\d+", mod_line):
                    break
                parts = mod_line.split()
                scan_type_code = parts[0]
                atoms = parts[1:-3]
                n_points = int(parts[-2])
                step_size = float(parts[-1])
                scan_type = {
                    "D": "Dihedral",
                    "A": "Angle",
                    "B": "Bond",
                    "R": "Distance"
                }.get(scan_type_code, "Unknown")
                scan_info = {
                    "type": scan_type,
                    "atoms": atoms,
                    "step": step_size,
                    "value0": None,
                    "value": None,
                    "value_mod": None
                }
                break
            break

    if scan_info:
        in_params = False
        for line in log_content:
            if "Initial Parameters" in line:
                in_params = True
                continue
            if in_params and "Scan" in line:
                fields = line.strip().split()
                try:
                    scan_idx = fields.index("Scan")
                    value0 = float(fields[scan_idx - 1])
                    scan_info["value0"] = value0
                except (ValueError, IndexError):
                    pass
                break

    return scan_info

def extract_scan_data(log_content):
    geometries = []
    energies = []
    scan_coords = []

    scan_info_template = parse_modredundant(log_content)

    current_geom = []
    current_point = 1
    i = 0
    n_lines = len(log_content)

    while i < n_lines:
        line = log_content[i]

        if "Input orientation:" in line or "Standard orientation:" in line:
            geom_block = []
            i += 5
            while i < n_lines and not "-----" in log_content[i]:
                parts = log_content[i].split()
                if len(parts) >= 6:
                    atom_number = int(parts[1])
                    x, y, z = map(float, parts[3:6])
                    geom_block.append((atom_number, x, y, z))
                i += 1
            current_geom = geom_block

        if "scan point" in line and "out of" in line:
            parts = line.strip().split()
            try:
                idx = parts.index("point") + 1
                current_point = int(parts[idx])
            except (ValueError, IndexError):
                pass

            while i < n_lines and "Optimization completed." not in log_content[i]:
                i += 1

            j = i
            energy = None
            while j > 0:
                if "SCF Done" in log_content[j]:
                    match = re.search(r"SCF Done:\s+E\(\w+\)\s+=\s+([-.\d]+)", log_content[j])
                    if match:
                        energy = float(match.group(1))
                        break
                j -= 1

            if current_geom and energy is not None:
                scan_info = scan_info_template.copy() if scan_info_template else {}
                if scan_info and scan_info.get("value0") is not None:
                    delta = (current_point - 1) * scan_info["step"]
                    raw_val = scan_info["value0"] + delta
                    scan_info["value"] = raw_val

                    if scan_info["type"] in ("Angle", "Dihedral"):
                        mod_val = raw_val % 360
                        #if scan_info["type"] == "Dihedral" and mod_val > 180:
                        #    mod_val -= 360
                        scan_info["value_mod"] = mod_val
                    else:
                        scan_info["value_mod"] = raw_val

                geometries.append(current_geom)
                energies.append(energy)
                scan_coords.append(scan_info)

            current_point += 1
        i += 1

    return geometries, energies, scan_coords

def write_sdf(geometries, energies, scan_coords, output_file):
    atom_symbols = {1: "H", 6: "C", 7: "N", 8: "O"}

    def sdf_block(geometry, energy, scan_info):
        lines = []
        lines.append("Generated by script")
        lines.append("Scan Structure")
        lines.append("")
        natoms = len(geometry)
        lines.append(f"{natoms:>3}  0  0  0  0  0            999 V2000")

        for atom_number, x, y, z in geometry:
            symbol = atom_symbols.get(atom_number, "X")
            lines.append(f"{x:10.4f}{y:10.4f}{z:10.4f} {symbol:<3} 0  0  0  0  0  0  0  0  0  0  0  0")

        lines.append("M  END")

        if energy is not None:
            lines.append(">  <Energy>")
            lines.append(f"{energy:.8f}")
            lines.append("")

        if scan_info:
            lines.append(">  <ScanType>")
            lines.append(scan_info["type"])
            lines.append("")

            lines.append(">  <ScanAtoms>")
            lines.append(" ".join(scan_info["atoms"]))
            lines.append("")

            if scan_info.get("value") is not None:
                lines.append(">  <ScanValue>")
                lines.append(f"{scan_info['value']:.4f}")
                lines.append("")
            if scan_info.get("value_mod") is not None:
                lines.append(">  <ScanValueMod360>")
                lines.append(f"{scan_info['value_mod']:.4f}")
                lines.append("")

        lines.append("$$$$")
        return "\n".join(lines)

    with open(output_file, "w") as sdf:
        for geom, energy, scan in zip(geometries, energies, scan_coords):
            sdf.write(sdf_block(geom, energy, scan))
            sdf.write("\n")

def display_results(energies, scan_coords, plot, csv_file=None):
    if not scan_coords or not energies:
        return
    e0 = energies[0]
    print(f"{'ScanValue':>12} {'Mod360':>10} {'Energy (Ha)':>15} {'Relative (kcal/mol)':>20}")
    print("-" * 65)
    scan_values = []
    scan_mods = []
    rel_energies = []
    for e, info in zip(energies, scan_coords):
        raw = info.get("value", None)
        mod = info.get("value_mod", None)
        rel = (e - e0) * 627.509 if e0 is not None else None
        print(f"{raw:12.4f} {mod:10.4f} {e:15.8f} {rel:20.4f}")
        scan_values.append(raw)
        scan_mods.append(mod)
        rel_energies.append(rel)

    if csv_file:
        with open(csv_file, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["ScanValue", "Mod360", "Energy_Hartree", "RelativeEnergy_kcal/mol"])
            for val, mod, e, rel in zip(scan_values, scan_mods, energies, rel_energies):
                writer.writerow([f"{val:.4f}", f"{mod:.4f}", f"{e:.8f}", f"{rel:.4f}"])
        print(f"[CSV] Exported scan profile to {csv_file}")

    if plot:
        unit = "degrees"
        if scan_coords[0]["type"] == "Bond":
            unit = "Å"
        elif scan_coords[0]["type"] == "Angle":
            unit = "degrees"
        plt.plot(scan_mods, rel_energies, marker='o')
        plt.xlabel(f"{scan_coords[0]['type']} (mod 360, {unit})")
        plt.ylabel("Relative Energy (kcal/mol)")
        atoms = " ".join(scan_coords[0]["atoms"])
        plt.title(f"{scan_coords[0]['type']} Scan for Atoms: {atoms}")
        plt.grid(True)
        plt.tight_layout()
        plt.show()

def main():
    parser = argparse.ArgumentParser(description="Extract scan structures and energies from Gaussian log.")
    parser.add_argument("-i", "--input", required=True, help="Gaussian log file")
    parser.add_argument("-o", "--output", required=True, help="Output SDF file")
    parser.add_argument("--plot", action="store_true", help="Plot relative energy profile")
    parser.add_argument("--csv", action="store_true", help="Also save CSV with energies")
    args = parser.parse_args()

    with open(args.input, "r") as f:
        log_content = f.readlines()

    geometries, energies, scan_coords = extract_scan_data(log_content)

    print(f"[INFO] Extracted {len(geometries)} scan points.")
    write_sdf(geometries, energies, scan_coords, args.output)

    csv_file = args.output.rsplit(".", 1)[0] + "_scan.csv" if args.csv else None
    display_results(energies, scan_coords, plot=args.plot, csv_file=csv_file)

if __name__ == "__main__":
    main()



